/// <reference types="cypress" />
// Workday application E2E test POC
// Work in progress, need to fix flaky test where listbox does not load
describe('workday e2e', () => {
    beforeEach(() => {
        cy.reload() 
        cy.log('I run before every test in every spec file!')
    })
    it(`search for job`, () => {
        cy.viewport("macbook-16")
        cy.visit("https://nandos.wd3.myworkdayjobs.com/Nandos")
        cy.waitFor(6000)
        cy.get('.WMJH > .gwt-TextBox', { timeout: 10000 })
            .should('be.visible')
            .type('N14SN') 
        cy.get('.WHH0').click()
        cy.waitFor(6000)
        cy.get('#promptOption-gwt-uid-10').click({force: true})
        cy.wait(5000)
        cy.get('[type="checkbox"]').first().check({force: true})
        cy.get('#promptOption-gwt-uid-231').click()
        cy.waitFor(6000)
        cy.contains('[data-automation-id="adventureButton"]', 'Apply').click()
        cy.waitFor(5000)
        cy.contains('[data-automation-id="applyManually"]', 'Apply Manually').click()
        cy.waitFor(6000)
        cy.get('[class="css-1j9bnzb"]', { timeout: 10000 }).contains('My Information')
        cy.get('[for="input-1"]').contains('How Did You Hear About Us?')
        cy.get('#input-1')
            .click()
        cy.wait(3000)
        cy.contains('[data-automation-label="Agency"]', 'Agency', { timeout: 10000 }).click()
        cy.wait(3000)
        cy.contains('[data-automation-label="Focus Cloud Ltd (Agency)"]', 'Focus Cloud Ltd (Agency)', { timeout: 10000 }).click()
        cy.get('[id=2]').check().should('be.checked')
        cy.get('[id="input-3"]')
            .contains('United Kingdom').should('have.class', 'css-1ntjusa')
        cy.get('#input-4').click()
        cy.get('[class="css-v9pk79"]')
            .get('div')
            .contains('Mr.')
            // need to use force true as element becomes detached from DOM -- 
            .click({force: true})
        cy.get('#input-5').should('be.visible').type("Joe")
        cy.get('#input-6').should('be.visible').type("Bloggs")
        cy.get('#input-8').should('be.visible').type("10 Downing Street")
        cy.get('#input-9').should('be.visible').type("City of London ")
        cy.get('#input-10').should('be.visible').type("SW1A 2AA")
        cy.get('#input-11').should('be.visible').type("jamesa@nandos.co.uk")
        cy.get('#input-12').should('be.visible').click()
        cy.get('#input-14').should('be.visible').type("07500111222")
        cy.get('div')
            .contains('Mobile')
            .click({force: true})
        cy.get('button').contains('Next').click()
        cy.get('[data-automation-id="resumeSection"]').contains('Resume/CV')
        cy.get("input[type=file]")
            .attachFile("testupload.docx")    
        cy.get('div.css-1k6yql2')
            .should("contain", 
            "Successfully Uploaded!")
        cy.get('button').contains('Next').click()
        cy.get('[data-automation-id="nonUSPersonalInfoSection"]')
            .should("contain",
            "Personal Information")
        cy.get('#input-692').click()
        cy.get('[data-value="62bdf6cda97801a5e4966d04fa004103"]')
            .should('be.visible')
            .contains('Male')
            .click()
        cy.get('#input-663').click()
        cy.get('[data-value="62bdf6cda9780189e051789d480106b2"]')
            .should('be.visible')
            .contains('No')
            .click()
        cy.get('#input-664').click()
        cy.get('[data-value="62bdf6cda978010a76d5839d480114b2"]')
            .should('be.visible')
            .contains('30 - 60 Minutes')
            .click()
        cy.get('#input-665').click()
        cy.get('[data-value="16df4d19970301f9c7aa8dece2010b3e"]')
            .should('be.visible')
            .contains('Yes')
            .click()
        cy.get('#input-666').click()
        cy.get('[data-value="62bdf6cda97801524c1b8f9d48011cb2"]')
            .should('be.visible')
            .contains('Any')
            .click()
        cy.get('#input-667').click()
        cy.get('[data-value="62bdf6cda97801c20466989e4801cbb2"]')
            .should('be.visible')
            .contains('Any')
            .click()
        cy.get('#input-668').click()
        cy.get('[data-value="62bdf6cda97801b3e38d949d480121b2"]')
            .should('be.visible')
            .contains('Any')
            .click()
        cy.get('#input-669').click()
        cy.get('[data-value="62bdf6cda97801959d4ba69d480134b2"]')
            .should('be.visible')
            .contains('16 - 25 Hours')
            .click()
        cy.get('#input-670').should('be.visible').type("test")
        cy.get('#input-671').should('be.visible').type("test2")
        cy.get('#input-672').should('be.visible').type("test3")
        cy.get('#input-673').click()
        cy.get('[data-value="62bdf6cda978012cb4085d9e4801a3b2"]')
            .contains('Prefer not to say')
            .click({force: true})
        cy.get('button').contains('Next').click({force: true})
    })    
})